services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        TOKENIZERS_PARALLELISM: ${TOKENIZERS_PARALLELISM}
        MARKETAUX_API_KEY: ${MARKETAUX_API_KEY}
        LLAMA_CLOUD_API_KEY: ${LLAMA_CLOUD_API_KEY}
        PORT: ${PORT}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
        INSTANCE_CONNECTION_NAME: ${INSTANCE_CONNECTION_NAME}
        GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
        DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./chromadb_data:/server/chromadb_data